### ISSUE TITLE
Função de débito

### ISSUE THREAD

**Issue by kaoecoito** [LinkNacional/integration-rede-for-woocommerce#10]
Olá @marcos-alexandre82 ,

Olhei a documentação do e-Rede e não parece ser absurdamente complexo implementar o débito.
Tenho um cliente que aceitou ativar a função que é necessária para isso na Rede (3D Secure) e me liberou para fazer alguns testes, se realmente funcionar vejo de colocar essa implementação.

**Comment by marcos-alexandre82** [comment]
@kaoecoito como estão seus testes com relação ao débito em seu outro projeto?

**Comment by andersontave** [comment]
Fala pessoal! Tudo bem?
Conseguiram implementar o débito em conta? Precisam de ajuda?

**Comment by GuilhermeLinkNacional** [comment]
Boa tarde, função débito está disponível na última atualização do plugin.
