### ISSUE TITLE
O plugin funciona em Multisite?

### ISSUE THREAD

**Issue by celiosat** [LinkNacional/integration-rede-for-woocommerce#13]
Criei 3 sites wordpress + elementor + woocommerce e estou estudando transforma-los em uma rede multisite.

Dentro do planejamento verifiquei que nem todos os plugins são compatíveis com multisite.

O plugins que você criou é compatível?

**Comment by marcos-alexandre82** [comment]
Olá,

Ainda não testei em multisites mas creio que funcione sim. Se puder fazer os testes em um ambiente de homologação e dar um retorno aqui, ficarei super agradecido ;)

**Comment by marcos-alexandre82** [comment]
@celiosat conseguiu testar? Consegue enviar um feedback sobre o funcionamento?

**Comment by emanuellopess** [comment]
Desde que o plugin do WooCommerce esteja corretamente configurado o método de pagamento da Rede é compatível com multi-site.
