### ISSUE TITLE
Atualização do plugin oficial

### ISSUE THREAD

**Issue by rickdroio** [LinkNacional/integration-rede-for-woocommerce#14]
Olá Marcos.
Tem algum plano de atualizar seu plugin para a mesma baseline do plugin oficial?
Eles fizeram uma atualização recente, testei e continua com alguns limitações... porém pode ser que venha algum bugfix.. 
Valeu!!

**Comment by marcos-alexandre82** [comment]
Olá,
Quero lançar ainda está semana uma atualização visual e a inclusão de um filtro no plugin:
https://github.com/marcos-alexandre82/integration-rede-for-woocommerce/tree/development

Se puder testar em um ambiente de homologação e me dar o feedback, ficarei agradecido ;)

Já com relação a função débito, presente agora no plugin do repositório da Rede, minha ideia era incorporar essa funcionalidade e lançar ainda este mês, porém eles estão revendo a regra de negócios acerca da função de antifraude:
https://github.com/DevelopersRede/rede-woocommerce/issues/27#event-3976072579

Então provavelmente eu aguarde essa decisão deles ;)
