### ISSUE TITLE
Mensagens de Erro - Não registradas no Pedido

### ISSUE THREAD

**Issue by netomarchiori** [LinkNacional/integration-rede-for-woocommerce#19]
Estou com um cenário estranho por aqui,

Vejo alguns pedidos cancelados com a mensagem que passou do tempo limite estabelecido pelo WooCommerce (a pessoa chegou até a tela de pagamento, tentou pagar de alguma forma e não conseguiu, WooCommerce cancelou o pedido depois de 15 minutos)

Quando abro o pedido, não vejo nenhuma nota adicionada ao pedido em si, porem nos logs de integracão vejo mensagens relacionadas a erro de:
Please enter a valid credit card number
Please enter cardholder name
Card expiration date must be future

É possível logar estes erros tambem no pedido? Obrigado!

**Comment by marcos-alexandre82** [comment]
Olá,

Você pode configurar o tempo limite nas opções do WooCommerce:
https://docs.woocommerce.com/document/definindo-as-configuracoes-do-woocommerce/#section-10

Os erros ficam apenas nos logs. Somente quando tem sucesso na aprovação é que vão ser inseridos dados sobre o método de pagamento no pedido ;)


Att,

**Comment by netomarchiori** [comment]
valeu @marcos-alexandre82 ! sim, acabei aumentando o tempo limite, mas ainda assim acabo ficando com um pedido cancelado por falha do usuário em digitar um cartão válido.

Valeu
