### ISSUE TITLE
Configuração de juros por parcelas

### ISSUE THREAD

**Issue by Junior-Cardoso** [LinkNacional/integration-rede-for-woocommerce#20]
Pessoal, eu queria configurar a compra pela Rede da seguinte forma... a partir da parcela dividida em 6x será tanto de juros... 7x, 8x, 9x e por aí vai.

Achei que esse tipo de coisa era para resolver com a própria e.Rede... mas quando liguei para eles, eles disseram que é uma configuração dentro do plugin.

No entanto, não consigo encontrar essa configuração... Alguém tem ideia de como resolver?

Não sou programador, mas se for pra ajeitar através de linhas de código tenho um parceiro que pode me ajudar.

**Comment by marcos-alexandre82** [comment]
Olá, @Junior-Cardoso .

O plugin não tem essa configuração, teria que ser trabalhado através de programação mesmo. Você pode pedir para seu parceiro verificar se o filtro que tem no plugin ajuda ele a montar a lógica que precisa ;)

**Comment by Junior-Cardoso** [comment]
Saquei, valeu @marcos-alexandre82. Vou tentar por aqui!
