### ISSUE TITLE
Pague com a Rede: Unsuccessful. Please, contact Rede.

### ISSUE THREAD

**Issue by BrunoBacsh** [LinkNacional/integration-rede-for-woocommerce#21]
Está acontecendo com alguns cartões mastercard que meus clientes estão tentando utilizar, é algum problema no plugin ou por parte da Rede? Obrigado desde já.

**Comment by marcos-alexandre82** [comment]
Creio que seja algum problema com os cartões, algo que esteja fazendo a Rede negar a compra.
Já testou alguns outros cartões Mastercard? Se sim, deu certo a finalização? Com cartões Visa a finalização ocorre normalmente?
Consegue entrar em contato com eles para ver o que está acontecendo e, se possível, colocar a solução aqui posteriormente?

Att,

**Comment by Rsenne01** [comment]
Olá também, estou tendo esse problema com um cliente.
Já utilizei outros cartões e a resposta é a mesma.
Obrigado

**Comment by marcos-alexandre82** [comment]
@Rsenne01 o erro está acontecendo apenas com a bandeira Mastercard? Já entrou em contato com o suporte da Rede e enviou o log para eles avaliarem o que pode estar ocorrendo?
