### ISSUE TITLE
Atualizar Certificado Digital Rede

### ISSUE THREAD

**Issue by SmarThiago** [LinkNacional/integration-rede-for-woocommerce#22]
Olá,

Muitos clientes da Rede estão recebendo e-mail e avisos para atualizar o certificado digital.

Mais informações do aviso no site da Rede: https://www.userede.com.br/content/userede/pt-br/documentos/certificado-digital-rede

Seu plugin da Rede para WooCommerce precisa ser atualizado? Você irá fazer essa atualização?

obrigado!

**Comment by emanuellopess** [comment]
O Plugin não necessita de certificado e vai continuar funcionando normalmente.
