### ISSUE TITLE
Problema com autocompletar

### ISSUE THREAD

**Issue by potter991** [LinkNacional/integration-rede-for-woocommerce#24]
Estou tendo problemas recorrentes com clientes que tentam preencher usando o autocompletar no chrome.
No log, parece que o autocompletar tenta colocar as informações de algum jeito errado, segue como fica:

"expirationMonth":"09\/2028","expirationYear":"20"

**Comment by rickdroio** [comment]
@potter991 utilize esse PR para resolver esse problema...

https://github.com/marcos-alexandre82/integration-rede-for-woocommerce/pull/16
