### ISSUE TITLE
integração Rede

### ISSUE THREAD

**Issue by esterps17** [LinkNacional/integration-rede-for-woocommerce#26]
Não consigo integrar a Rede no Woocommerce
Da erro: Cartão de Crédito: ExpirationMonth: Invalid parameter format.
Alguem sabe o que é?

**Comment by marcos-alexandre82** [comment]
Olá,

Aparentemente o problema está resolvido com a nova atualização que lancei agora no repositório do WordPress (2.1.1).

Conseguem avaliar e me dar um feedback se está tudo correto?

:)

**Comment by esterps17** [comment]
Acabei de atualizar o plugin e gerei um token novo na Rede, e mesmo assim
continua não autorizando o pagamento com cartão.
Dá a mensagem: Not enabled for this merchant.

Não consigo identificar onde está o erro.


Em ter., 27 de jul. de 2021 21:54, Marcos Alexandre <
***@***.***> escreveu:

**Comment by marcos-alexandre82** [comment]
@esterps17 pela mensagem de erro me parece que é algo relacionado ao seu cadastro junto a Rede. Tente entrar em contato com o suporte deles que devem resolver :)
