### ISSUE TITLE
Problemas no Status do Pedido - WooCommerce

### ISSUE THREAD

**Issue by marcelonowe** [LinkNacional/integration-rede-for-woocommerce#28]
Realizei a integração conforme instruções, o pagamento ocorreu normalmente, foi debitado no cartão de crédito o valor da compra de testes R$ 1,00.

Porém no Woocommerce o status do pedido continua constando como pendente.

![image](https://user-images.githubusercontent.com/94914906/143043179-30a6d333-f3a0-4672-9245-ac5c0d6de23c.png)
![image](https://user-images.githubusercontent.com/94914906/143043255-63e81a89-d2ad-4731-9d7b-d1d1c32707ce.png)
![image](https://user-images.githubusercontent.com/94914906/143043330-1512b910-6740-4baf-bbd4-1b56265a8a6f.png)

Existe alguma configuração extra a ser feita para que o status seja atualizado automáticamente?

**Comment by marcos-alexandre82** [comment]
@marcelonowe seu teste foi feito em ambiente de produção com um cartão real, certo? Neste caso, precisa que o banco/administradora do cartão confirme a operação. Só depois que o WooCommerce receber essa confirmação, ele vai alterar o status do pedido ;)

**Comment by marcelonowe** [comment]
Resolvido aqui, obrigado mestre!
