### ISSUE TITLE
Certificado Digital Rede - 2022

### ISSUE THREAD

**Issue by marcelocastelobranco76** [LinkNacional/integration-rede-for-woocommerce#29]
Boa tarde.
Tenho um cliente que utiliza o plugin Rede Woocommerce. Esse cliente recebeu um e-mail da Rede com a mensagem abaixo:
"Caso a atualização não seja realizada, sua operação com a Rede corre o risco de ser interrompida, siga a data limite para efetuá-la: até o dia 19 de março de 2022, às 00h."
Minha dúvida é a seguinte:
O plugin utiliza o certificado digital da Rede? E se utiliza tem o risco de parar de funcionar se o certificado digital for atualizado ?

**Comment by marcos-alexandre82** [comment]
Olá, @marcelocastelobranco76 . Acredito que seja o mesmo item deste tópico:

https://wordpress.org/support/topic/atualizacao-do-certificado-digital-rede/#post-14342311

Att,
