### ISSUE TITLE
Ocorreu um erro: A data de expiração deve ser futura.

### ISSUE THREAD

**Issue by baitasite** [LinkNacional/integration-rede-for-woocommerce#31]
Olá meus queridos, tudo certo?

Um cliente reportou essa mensagem:

"Ocorreu um erro: A data de expiração deve ser futura."

Pensado, será que ele está com cartão expirado? Na realidade não está e mesmo assim ocorreu, saberiam o que pode ser?

**Comment by marcos-alexandre82** [comment]
@baitasite sabe se foi apenas com um cartão? Os demais clientes tem relatado o mesmo problema?

Pode ser que algum tema ou plugin tenha interferido, fazendo o plugin não interpretar corretamente os dados, pois ele ignora os dois primeiros dígitos e lê apenas os dois últimos, então se algo interferiu, ele acabou lendo os dois primeiros e interpretou como o ano, por exemplo, se o cartão vence em 2023, ao invés de ler "23" ele leu "20".

Talvez até algo no navegador do usuário tenha desativado o JS.

Att,
