### ISSUE TITLE
Alteração de produtos no pedido

### ISSUE THREAD

**Issue by eduardorph** [LinkNacional/integration-rede-for-woocommerce#33]
Como funciona se o admin adicionar ou excluir produtos de um pedido já realizado, de alguma forma o novo valor é atualizado na rede também?

**Comment by emanuellopess** [comment]
Caso o administrador do site atualize o pedido ao recarregar a página de finalizar compra o plugin vai detectar o novo valor e fará a cobrança  normalmente.
