### ISSUE TITLE
Atualização do Integração Rede para WooCommerce

### ISSUE THREAD

**Issue by elcuadrocontato** [LinkNacional/integration-rede-for-woocommerce#34]
Boa tarde nosso site utiliza muito o plug in Integração Rede para WooCommerce, mas vimos que ele não é atualizado a bastante tempo. Existe algum plano para isso acontecer ?  Meu receio que se lance alguma nova versão do WOOCOMMERCE que este plugin pare de funcionar

**Comment by GuilhermeLinkNacional** [comment]
Boa tarde, o plugin foi plugin atualizado recentemente.
