### ISSUE TITLE
Repetindo pedidos e repetindo os pagamentos.

### ISSUE THREAD

**Issue by clayton-ramalho-silva** [LinkNacional/integration-rede-for-woocommerce#36]
Boa tarde. Estou como seguinte problema.
Quando o cliente faz um pedido e faz o pagamento. O pedido se repete e passa o cartão novamente. Com os mesmos produtos e valores.
Obrigado.

**Comment by marcusrfaust** [comment]
+1

**Comment by GuilhermeLinkNacional** [comment]
Boa tarde, foi resolvido na última atualização do plugin.
