### ISSUE TITLE
Não Estou Conseguindo Fazer Pagamentos com o Plugin

### ISSUE THREAD

**Issue by Guilherme-Nicoletti** [LinkNacional/integration-rede-for-woocommerce#40]
Olá, Tudo bem?

O plugin esta em modo de Testes, já inserir todas as informações, como Token, PV e etc, mas ao tentar Finalizar uma Compra, esta dando o seguinte erro: Affiliation: Invalid parameter format

Que não sei qual parametro esta dando problema, alguém consegue me ajudar?

**Comment by marcos-alexandre82** [comment]
@Guilherme-Nicoletti você preencheu algo nos campos "Configurações do parceiro"? Se sim (pelo que parece no erro), deixe em branco e coloque apenas o PV e Token.

Bom também verificar com o suporte da Rede se a conta e o PV/Token estão corretos e habilitados ;)

**Comment by Guilherme-Nicoletti** [comment]
@marcos-alexandre82 Sim, os campos PV e Token estão corretos, falei com o suporte da Rede, e não esta preenchido os dados de Parceiro, mas ainda continua dando o erro "Affiliation: Invalid parameter format."

**Comment by Guilherme-Nicoletti** [comment]
@marcos-alexandre82  conversei com o suporte de E-commerce da Rede, e me informaram que as integrações com o Woocommerce e Wordpress foram encerradas, que somente é possível agora por meio da MaxiPago, um serviço pago da propria Rede com o banco Itau, não sei se isso é verdade, mas foi o que me passaram por telefone, como plugin foi desenvolvido por voce, queria estar confirmando essas informações, ou se é somente um erro do plugin com a nova atualização do Wordpress ou do Woocommerce, Obrigado @marcos-alexandre82

**Comment by marcos-alexandre82** [comment]
@Guilherme-Nicoletti vi que realmente o repositório da Rede não tem mais o plugin do WooCommerce, que foi a base para este meu plugin. Na versão mais atualizada deles, tinha a opção de pagamento via débito, o que não tem no meu plugin.

Pelo que vi, o repositório da MaxiPago também está desatualizado e é o que indicam no site da Rede.

O meu plugin, ao menos na versão de produção, continua funcionando (foi feito um teste hoje). Talvez tenham removido as credencias de testes, pois a minha também está dando o mesmo erro  "Affiliation: Invalid parameter format." (testei aqui tbm).

Imagino que, ou o suporte da Rede indica onde conseguir o plugin atualizado da MaxiPago ou pode verificar com o suporte da Loja5 (plugin pago, mas com opção de débito e crédito) se ele ainda continua funcionando:

https://www.loja5.com.br/plugin-de-pagamento-e-rede-api-cartao-de-credito-e-debito-para-woocommerce-p652c271c285.html

**Comment by Guilherme-Nicoletti** [comment]
@marcos-alexandre82 Bacana, que bom saber que esta funcionando, confirmei os dados com o suporte do e-commerce da Rede, e o PV estava errado mesmo, mas agora esta dando outro erro, e liguei novamente pra Rede e me informaram que a conta não possui nenhum bloqueio, o erro é o seguinte:  Softdescriptor: Not enabled for this merchant.

Nas configurações o soft descriptor esta como FACHINI AUTO PECAS, foi o que a Rede me passou pra colocar, sabes me dizer se esta certo isso?

**Comment by Guilherme-Nicoletti** [comment]
@marcos-alexandre82  e quando deixo esse campo em branco do Soft Descriptor e tento fazer a compra, ele da o seguinte erro: Unauthorized. Identified moderate risk by the issuer.

**Comment by marcos-alexandre82** [comment]
@Guilherme-Nicoletti fiz na sexta a instalação em mais um site e está funcionando normalmente. Neste caso específico, a cliente não tinha o cadastro para utilizar em loja virtual, mas já utilizava a maquininha na loja física. A gerente da conta dela na Rede liberou para utilização para vendas online e ela recebeu o token e PV pode e-mail. Com isto, bastou colocar na configuração do plugin, deixando o Soft Description em branco e selecionando a opção "Produção" em "Tipo de ambiente".

Foi colocado o número máximo de vezes que ela vai aceitar o parcelamento e o valor mínimo de cada parcela, por exemplo, 30.00.

"Configuração de parceiros" também deixe em branco. Ative os logs e, depois de testar, se der erro ainda, poste aqui a saída dos logs para vermos o que pode estar errado ;)

Teste utilizando um tema padrão, como o Storefront, e deixe ativo apenas o plugin do WooCommerce, da Rede e o Brazilian Marcket on WooCommerce, para ver se é algum conflito com o tema ou outro plugin, caso os passos acima ainda gerem erro.

Ah, também veja com a Rede se o PV e Token são de "Produção" ;)

Recomendo colocar um produto de teste de R$ 1.00 e fazer uma compra real.

**Comment by Guilherme-Nicoletti** [comment]
@marcos-alexandre82 Boa tarde Marcos, Tudo bem?

Segui os passos que me passou na ultima conversa, e acabei achando o erro que estava bloqueando, e não vai acreditar, o que estava bloqueando e dando erro era na configuração do plugin, na opção: **Valor da menor parcela**, que tinha colocado como valor "1" nesse formato, e ao alterar para o formato de dinheiro, com virgula "0,00" ou "1,00" ele começou a funcionar, mas antes disso realmente estavamos com PV errado e fomos corrigindo aos poucos, que eram informações que a REDE tinha passado errado a nós, mas deixo minha mensagem de agradecimento para voce, pela realização desse plugin e pela atenção que teve comigo aqui no forúm! Muito obrigado!
