### ISSUE TITLE
Método de pagamento escondendo formas de pagamento e campos não renderizados

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/integration-rede-for-woocommerce#72]
Cliente relata:
Atualizei ontem para a versão 3.1.0 e quando fiz meu teste ele só mostrou a foto do cartão na parte superior e o campo nome para preencher, além de ocultar minha outra forma de pagamento. Voltei para a versão 3.0.5 e tudo voltou ao normal.

Necessário revisar como faz a renderização e possível problema de colisão.

[Link do fórum](https://wordpress.org/support/topic/bug-in-version-3-1-0/)

**Comment by emanuellopess** [comment]
@GuilhermeLinkNacional Priorize essa issue

**Comment by GuilhermeLinkNacional** [comment]
Corrigido
