### ISSUE TITLE
Erro de renderização em faturas/link de pagamento

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/integration-rede-for-woocommerce#75]
Problema ocorre na página de link de pagamento, necessário verificar se algum evento do script wooRedeDebit.js está referenciando elementos DOM inexistentes, possívelmente necessita de validação adicional

![image](https://github.com/user-attachments/assets/7ecb5b29-6579-4a0b-a3ab-acfdf0cd5f8e)

**Comment by GuilhermeLinkNacional** [comment]
Corrigido
